/**
 * @file GameManagerTests.cpp
 * @author TV1 (Duong)
 * @brief Regression tests for the GameManager state STACK and SAFE DEFERRED
 *        state operations (S6-TV1-16) and the overlay lifecycle (S6-TV1-17).
 */

#include <cassert>
#include <iostream>
#include <memory>
#include <string>

#include "core/GameManager.h"
#include "states/IGameState.h"
#include "patterns/InputState.h"

namespace {

// Shared, observable counters for a state that is owned by GameManager.
struct ProbeData {
    int enters = 0;
    int exits = 0;
    int pauses = 0;
    int resumes = 0;
    bool overlay = false;
    std::string name;
};

class ProbeState : public IGameState {
public:
    explicit ProbeState(std::shared_ptr<ProbeData> data) : m_data(std::move(data)) {}

    void onEnter() override { m_data->enters++; }
    void onExit() override { m_data->exits++; }
    void onPause() override { m_data->pauses++; }
    void onResume() override { m_data->resumes++; }
    void update(float) override {}
    void processEvents(const sf::Event&) override {}
    void processInput(const InputState&) override {}
    void render(sf::RenderTarget&) override {}
    bool isOverlay() const override { return m_data->overlay; }

private:
    std::shared_ptr<ProbeData> m_data;
};

// A state that queues a CHANGE to a target state from its onEnter callback.
// Used to prove an operation generated by a lifecycle callback is deferred.
class RerouteState : public IGameState {
public:
    explicit RerouteState(const std::shared_ptr<ProbeData>& target) : m_target(target) {}

    void onEnter() override {
        GameManager::getInstance().changeState(std::make_unique<ProbeState>(m_target));
    }
    void onExit() override {}
    void onPause() override {}
    void onResume() override {}
    void update(float) override {}
    void processEvents(const sf::Event&) override {}
    void processInput(const InputState&) override {}
    void render(sf::RenderTarget&) override {}
    bool isOverlay() const override { return false; }

private:
    std::shared_ptr<ProbeData> m_target;
};

void setUp() {
    // Replace whatever the singleton currently holds with a single clean state.
    GameManager::getInstance().changeState(std::make_unique<ProbeState>(std::make_shared<ProbeData>()));
    GameManager::getInstance().update(0.016f);
    GameManager::getInstance().popState();
    GameManager::getInstance().update(0.016f);
}

bool testStackLifecycle() {
    std::cout << "[RUNNING] testStackLifecycle..." << std::endl;
    setUp();

    auto& gm = GameManager::getInstance();
    auto a = std::make_shared<ProbeData>(); a->name = "A";
    auto b = std::make_shared<ProbeData>(); b->name = "B";

    gm.changeState(std::make_unique<ProbeState>(a));
    gm.update(0.016f);                                   // CHANGE -> A onEnter
    assert(gm.stackDepth() == 1);
    assert(a->enters == 1 && a->exits == 0);

    gm.pushState(std::make_unique<ProbeState>(b));
    gm.update(0.016f);                                   // A onPause, B onEnter
    assert(gm.stackDepth() == 2);
    assert(a->pauses == 1);
    assert(b->enters == 1);

    gm.popState();
    gm.update(0.016f);                                   // B onExit, A onResume
    assert(gm.stackDepth() == 1);
    assert(b->exits == 1);
    assert(a->resumes == 1);

    gm.popState();
    gm.update(0.016f);                                   // A onExit
    assert(gm.stackDepth() == 0);
    assert(a->exits == 1);

    std::cout << "[PASSED] testStackLifecycle" << std::endl;
    return true;
}

bool testDeferredOpFromCallback() {
    std::cout << "[RUNNING] testDeferredOpFromCallback..." << std::endl;
    setUp();

    auto& gm = GameManager::getInstance();
    auto finalData = std::make_shared<ProbeData>(); finalData->name = "FINAL";

    gm.changeState(std::make_unique<RerouteState>(finalData));
    gm.update(0.016f);
    // RerouteState entered and queued a CHANGE to finalData FROM onEnter. Because
    // processPendingOps snapshots the queue, that new op is deferred, so the stack
    // must still have exactly one state (RerouteState) — finalData not yet entered.
    assert(gm.stackDepth() == 1);
    assert(finalData->enters == 0);

    // Next safe point applies the deferred CHANGE -> finalData entered.
    gm.update(0.016f);
    assert(finalData->enters == 1);
    assert(gm.stackDepth() == 1);

    gm.popState();
    gm.update(0.016f);
    assert(gm.stackDepth() == 0);

    std::cout << "[PASSED] testDeferredOpFromCallback" << std::endl;
    return true;
}

bool testChangeExitsAllStackedStates() {
    std::cout << "[RUNNING] testChangeExitsAllStackedStates..." << std::endl;
    setUp();

    auto& gm = GameManager::getInstance();
    auto a = std::make_shared<ProbeData>(); a->name = "A";
    auto b = std::make_shared<ProbeData>(); b->name = "B"; b->overlay = true;

    gm.changeState(std::make_unique<ProbeState>(a));
    gm.update(0.016f);
    gm.pushState(std::make_unique<ProbeState>(b));
    gm.update(0.016f);
    assert(gm.stackDepth() == 2);

    // A hard CHANGE while an overlay is on top must exit BOTH stacked states.
    gm.changeState(std::make_unique<ProbeState>(std::make_shared<ProbeData>()));
    gm.update(0.016f);
    assert(gm.stackDepth() == 1);
    assert(a->exits == 1);
    assert(b->exits == 1);

    gm.popState();
    gm.update(0.016f);
    assert(gm.stackDepth() == 0);

    std::cout << "[PASSED] testChangeExitsAllStackedStates" << std::endl;
    return true;
}

} // namespace

int main() {
    const bool ok = testStackLifecycle()
                 && testDeferredOpFromCallback()
                 && testChangeExitsAllStackedStates();

    if (ok) {
        std::cout << "All GameManager tests passed successfully!" << std::endl;
        return 0;
    }
    std::cout << "GameManager tests FAILED." << std::endl;
    return 1;
}

